export const LEADERS = [
  { id: 1, name: "Adele Waugaman", role: "Senior Program Officer, AI Innovations", org: "Gates Foundation", country: "USA", region: "North America", expertise: ["AI & Machine Learning", "Digital Health Policy"], sector: "Philanthropy", language: "English", bio: "Senior leader at the intersection of technology, policy, and philanthropy with over 15 years experience driving cross-sector collaboration to scale digital transformation in emerging markets.", featured: true, image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
  { id: 2, name: "Dr. Amina Hassan", role: "Chief Digital Health Officer", org: "Ministry of Health Kenya", country: "Kenya", region: "Sub-Saharan Africa", expertise: ["Health Information Systems", "mHealth"], sector: "Government", language: "English, Swahili", bio: "Leading Kenya's national digital health transformation strategy, with a focus on interoperability and community health worker digital tools.", featured: true, image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
  { id: 3, name: "Dr. Priya Sharma", role: "Director, Digital Health Programmes", org: "WHO South-East Asia", country: "India", region: "South & Southeast Asia", expertise: ["Health Data Governance", "AI & Machine Learning"], sector: "Multilateral", language: "English, Hindi", bio: "Driving WHO's digital health agenda across 11 countries in South-East Asia, specialising in data governance frameworks and responsible AI in health.", featured: false, image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
  { id: 4, name: "Fatima Al-Rashid", role: "Founder & CEO", org: "HealthTech Arabia", country: "Jordan", region: "Middle East & North Africa", expertise: ["Digital Health Entrepreneurship", "Women's Health"], sector: "Private Sector", language: "English, Arabic", bio: "Building the MENA region's leading digital health venture, focused on maternal health and reproductive rights through mobile-first platforms.", featured: true, image: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
  { id: 5, name: "Dr. Claudia Mendes", role: "Research Lead, Digital Health Equity", org: "Fiocruz", country: "Brazil", region: "Latin America & Caribbean", expertise: ["Health Equity", "Community Health"], sector: "Academia", language: "English, Portuguese, Spanish", bio: "Leading research on digital health equity across Brazil's Unified Health System, with particular focus on Afro-Brazilian and indigenous communities.", featured: false, image: "https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
  { id: 6, name: "Sarah Okonkwo", role: "Programme Manager, Digital Health", org: "USAID", country: "Nigeria", region: "Sub-Saharan Africa", expertise: ["mHealth", "Health Information Systems"], sector: "Government", language: "English", bio: "Managing USAID's digital health portfolio across West Africa, supporting national digital health strategies and interoperability initiatives.", featured: false, image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
  { id: 7, name: "Dr. Li Wei", role: "Associate Professor, Global Health Informatics", org: "Peking University", country: "China", region: "East Asia & Pacific", expertise: ["Health Information Systems", "AI & Machine Learning"], sector: "Academia", language: "English, Mandarin", bio: "Researching AI applications in population health management and health systems strengthening, with publications in leading global health journals.", featured: false, image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
  { id: 8, name: "Nomvula Dlamini", role: "Head of Digital Innovation", org: "African Union Development Agency", country: "South Africa", region: "Sub-Saharan Africa", expertise: ["Digital Health Policy", "Health Data Governance"], sector: "Multilateral", language: "English, Zulu, Xhosa", bio: "Shaping continental digital health policy for 55 member states, championing Africa-led data governance frameworks and open health standards.", featured: true, image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face", linkedin: "https://linkedin.com" },
];

export const REGIONS = ["All regions", "Sub-Saharan Africa", "South & Southeast Asia", "Latin America & Caribbean", "Middle East & North Africa", "North America", "East Asia & Pacific", "Europe & Central Asia"];
export const EXPERTISE_AREAS = ["All expertise", "AI & Machine Learning", "Digital Health Policy", "Health Data Governance", "mHealth", "Health Information Systems", "Health Equity", "Women's Health", "Community Health", "Digital Health Entrepreneurship"];
export const SECTORS = ["All sectors", "Government", "Philanthropy", "Multilateral", "Academia", "Private Sector", "Civil Society"];

export const NAV_SECTIONS = [
  { id: "overview", label: "Overview" },
  { id: "brief", label: "The Brief" },
  { id: "platform", label: "Platform" },
  { id: "visualisation", label: "Visualisation" },
  { id: "directory", label: "Directory Demo" },
  { id: "questions", label: "Discovery Qs" },
  { id: "examples", label: "Profile" },
  // { id: "fee", label: "Fee & Timeline" },
];
